### ISSUE TITLE
动态修改标题的默认值

### ISSUE THREAD

**Issue by sca-rab** [boomcx/spinner_box#2]
作者你好，目前我在使用本插件时遇到了一些问题，简要描述如下：

有页面A和页面B，页面B用rebuilder方法构建了筛选下拉框。从A跳转到B时携带参数，根据参数不同，需要：1.筛选下拉框默认选中不同的选项，2.下拉框标题显示为该选项名称并高亮。

目前1已实现，请教有2有实现的方法么？

**Comment by boomcx** [comment]
插件目前采用为头部、弹窗分离式设计，所以初始化选中标题，需要额外操作：
尝试构建完成后使用  `_controler.updateName('name', index: 0);`。
示例路径：exampale->lib->pages->init.dart。

eg：后续会升级成完整的数据驱动模式（通过设置参数`SpinnerItemData`中`select`值设置，来默认显示选项卡已选中项）。
